Update FirstAction.yml

diff --git a/.github/workflows/FirstAction.yml b/.github/workflows/FirstAction.yml
--- a/.github/workflows/FirstAction.yml
+++ b/.github/workflows/FirstAction.yml
@@ -6,7 +6,7 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
 
     steps:
       # 1. Checkout code
@@ -20,6 +20,17 @@ jobs:
           distribution: 'temurin'
           java-version: '17'
 
+      # 3. Install Maven if missing
+      - name: Ensure Maven is installed
+        run: |
+          if ! command -v mvn &> /dev/null; then
+            echo "Maven not found. Installing..."
+            sudo dnf install -y maven
+          else
+            echo "Maven is already installed"
+          fi
+          mvn -version
+
       # 3. Build with Maven
       - name: Build with Maven
         run: mvn clean package -DskipTests
@@ -32,7 +43,7 @@ jobs:
           path: target/*.war
 
   deploy:
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
     needs: build
     environment: production
 
@@ -42,7 +53,8 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: myapp
-          # 6. Deploy WAR via Tomcat Manager
+
+      # 6. Deploy WAR via Tomcat Manager
       - name: Deploy to Tomcat
         run: |
           WAR_FILE=$(ls *.war)
